version: '3.8'


services:
  app:
    image: aravind2000/custom
    ports:
      - '8100:8100'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/custom?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: custom
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin


